import { BuildingId, BuildingDefinition, Era } from '../types/buildings.js';
import { ResourceType } from '../types/resources.js';

export const BUILDING_DEFINITIONS: Record<BuildingId, BuildingDefinition> = {
  // ─── Era 1: Aldea ────────────────────────────────────────
  [BuildingId.Choza]: {
    id: BuildingId.Choza,
    name: 'Choza',
    description: 'Simple dwelling that shelters your citizens.',
    era: Era.Aldea,
    baseCost: { [ResourceType.Wood]: 20, [ResourceType.Food]: 10 },
    costMultiplier: 1.15,
    maxLevel: 10,
    constructionTicks: 3,
    populationCapacity: 5,
    happinessBonus: 1,
  },
  [BuildingId.Granja]: {
    id: BuildingId.Granja,
    name: 'Granja',
    description: 'Produces food to sustain your growing population.',
    era: Era.Aldea,
    baseCost: { [ResourceType.Wood]: 25, [ResourceType.Stone]: 10 },
    costMultiplier: 1.15,
    maxLevel: 10,
    constructionTicks: 4,
    production: { [ResourceType.Food]: 5 },
  },
  [BuildingId.Aserradero]: {
    id: BuildingId.Aserradero,
    name: 'Aserradero',
    description: 'Harvests wood from the surrounding terrain.',
    era: Era.Aldea,
    baseCost: { [ResourceType.Wood]: 15, [ResourceType.Stone]: 15 },
    costMultiplier: 1.15,
    maxLevel: 10,
    constructionTicks: 4,
    production: { [ResourceType.Wood]: 4 },
  },
  [BuildingId.Mina]: {
    id: BuildingId.Mina,
    name: 'Mina',
    description: 'Extracts stone and iron from the earth.',
    era: Era.Aldea,
    baseCost: { [ResourceType.Wood]: 30, [ResourceType.Food]: 15 },
    costMultiplier: 1.15,
    maxLevel: 10,
    constructionTicks: 5,
    production: { [ResourceType.Stone]: 3, [ResourceType.Iron]: 1 },
  },
  [BuildingId.Almacen]: {
    id: BuildingId.Almacen,
    name: 'Almacen',
    description: 'Increases the storage capacity for all resources.',
    era: Era.Aldea,
    baseCost: { [ResourceType.Wood]: 40, [ResourceType.Stone]: 20 },
    costMultiplier: 1.15,
    maxLevel: 10,
    constructionTicks: 4,
    storageBonus: 200,
  },
  [BuildingId.Muralla]: {
    id: BuildingId.Muralla,
    name: 'Muralla',
    description: 'Defensive wall that protects your settlement from raids.',
    era: Era.Aldea,
    baseCost: { [ResourceType.Stone]: 35, [ResourceType.Wood]: 15 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 6,
    defenseBonus: 10,
  },
  [BuildingId.Mercado]: {
    id: BuildingId.Mercado,
    name: 'Mercado',
    description: 'Enables trade with other players and boosts happiness.',
    era: Era.Aldea,
    baseCost: { [ResourceType.Wood]: 30, [ResourceType.Stone]: 20, [ResourceType.Food]: 10 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 5,
    happinessBonus: 3,
  },

  // ─── Era 2: Pueblo ───────────────────────────────────────
  [BuildingId.Herreria]: {
    id: BuildingId.Herreria,
    name: 'Herreria',
    description: 'Forges iron into tools and weapons, unlocking advanced units.',
    era: Era.Pueblo,
    baseCost: { [ResourceType.Wood]: 50, [ResourceType.Stone]: 40, [ResourceType.Iron]: 20 },
    costMultiplier: 1.15,
    maxLevel: 8,
    constructionTicks: 8,
    production: { [ResourceType.Iron]: 3 },
    techRequired: 'ironworking',
  },
  [BuildingId.Cuartel]: {
    id: BuildingId.Cuartel,
    name: 'Cuartel',
    description: 'Trains military units to defend or attack.',
    era: Era.Pueblo,
    baseCost: { [ResourceType.Wood]: 60, [ResourceType.Stone]: 40, [ResourceType.Iron]: 15 },
    costMultiplier: 1.15,
    maxLevel: 8,
    constructionTicks: 8,
    defenseBonus: 5,
    techRequired: 'military_tactics',
  },
  [BuildingId.Torre]: {
    id: BuildingId.Torre,
    name: 'Torre de Vigilancia',
    description: 'Watchtower that provides vision and defense bonus.',
    era: Era.Pueblo,
    baseCost: { [ResourceType.Stone]: 60, [ResourceType.Iron]: 10 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 6,
    defenseBonus: 15,
    techRequired: 'masonry',
  },
  [BuildingId.Puerto]: {
    id: BuildingId.Puerto,
    name: 'Puerto',
    description: 'Coastal trade hub that generates gems from maritime commerce.',
    era: Era.Pueblo,
    baseCost: { [ResourceType.Wood]: 70, [ResourceType.Stone]: 30, [ResourceType.Iron]: 10 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 10,
    production: { [ResourceType.Gems]: 1 },
    happinessBonus: 2,
    techRequired: 'navigation',
  },
  [BuildingId.Biblioteca]: {
    id: BuildingId.Biblioteca,
    name: 'Biblioteca',
    description: 'Accelerates research and unlocks advanced technologies.',
    era: Era.Pueblo,
    baseCost: { [ResourceType.Wood]: 50, [ResourceType.Stone]: 50, [ResourceType.Gems]: 5 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 8,
    happinessBonus: 2,
    techRequired: 'writing',
  },
  [BuildingId.Templo]: {
    id: BuildingId.Templo,
    name: 'Templo',
    description: 'Sacred place that generates mana and boosts happiness.',
    era: Era.Pueblo,
    baseCost: { [ResourceType.Stone]: 60, [ResourceType.Gems]: 10 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 10,
    production: { [ResourceType.Mana]: 1 },
    happinessBonus: 5,
    techRequired: 'mysticism',
  },

  // ─── Era 3: Ciudad ───────────────────────────────────────
  [BuildingId.Universidad]: {
    id: BuildingId.Universidad,
    name: 'Universidad',
    description: 'Center of higher learning that dramatically speeds research.',
    era: Era.Ciudad,
    baseCost: { [ResourceType.Stone]: 120, [ResourceType.Iron]: 40, [ResourceType.Gems]: 15 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 15,
    happinessBonus: 3,
    techRequired: 'education',
  },
  [BuildingId.Fortaleza]: {
    id: BuildingId.Fortaleza,
    name: 'Fortaleza',
    description: 'Massive fortification that provides overwhelming defense.',
    era: Era.Ciudad,
    baseCost: { [ResourceType.Stone]: 150, [ResourceType.Iron]: 80, [ResourceType.Wood]: 50 },
    costMultiplier: 1.15,
    maxLevel: 3,
    constructionTicks: 20,
    defenseBonus: 40,
    techRequired: 'fortification',
  },
  [BuildingId.Banco]: {
    id: BuildingId.Banco,
    name: 'Banco',
    description: 'Financial institution that generates tokens and gems.',
    era: Era.Ciudad,
    baseCost: { [ResourceType.Stone]: 100, [ResourceType.Iron]: 30, [ResourceType.Gems]: 20 },
    costMultiplier: 1.15,
    maxLevel: 5,
    constructionTicks: 12,
    production: { [ResourceType.Gems]: 2 },
    techRequired: 'currency',
  },
  [BuildingId.Gremio]: {
    id: BuildingId.Gremio,
    name: 'Gremio',
    description: 'Guild hall that boosts all production buildings.',
    era: Era.Ciudad,
    baseCost: { [ResourceType.Wood]: 80, [ResourceType.Stone]: 80, [ResourceType.Iron]: 40 },
    costMultiplier: 1.15,
    maxLevel: 3,
    constructionTicks: 12,
    happinessBonus: 4,
    techRequired: 'guilds',
  },
  [BuildingId.Arena]: {
    id: BuildingId.Arena,
    name: 'Arena',
    description: 'Entertainment venue that provides a large happiness boost.',
    era: Era.Ciudad,
    baseCost: { [ResourceType.Stone]: 100, [ResourceType.Wood]: 60, [ResourceType.Iron]: 20 },
    costMultiplier: 1.15,
    maxLevel: 3,
    constructionTicks: 10,
    happinessBonus: 10,
    techRequired: 'entertainment',
  },
  [BuildingId.Observatorio]: {
    id: BuildingId.Observatorio,
    name: 'Observatorio',
    description: 'Astronomical observatory that generates mana and boosts research.',
    era: Era.Ciudad,
    baseCost: { [ResourceType.Stone]: 90, [ResourceType.Gems]: 25, [ResourceType.Mana]: 10 },
    costMultiplier: 1.15,
    maxLevel: 3,
    constructionTicks: 14,
    production: { [ResourceType.Mana]: 3 },
    techRequired: 'astronomy',
  },

  // ─── Era 4: Metropolis ───────────────────────────────────
  [BuildingId.Maravilla]: {
    id: BuildingId.Maravilla,
    name: 'Maravilla',
    description: 'A monumental wonder that provides massive bonuses to all aspects of your civilization.',
    era: Era.Metropolis,
    baseCost: {
      [ResourceType.Wood]: 300,
      [ResourceType.Stone]: 400,
      [ResourceType.Iron]: 200,
      [ResourceType.Gems]: 100,
      [ResourceType.Mana]: 50,
    },
    costMultiplier: 1.15,
    maxLevel: 1,
    constructionTicks: 60,
    production: { [ResourceType.Gems]: 5, [ResourceType.Mana]: 5 },
    defenseBonus: 20,
    happinessBonus: 15,
    storageBonus: 500,
    techRequired: 'architecture',
  },
  [BuildingId.Portal]: {
    id: BuildingId.Portal,
    name: 'Portal Dimensional',
    description: 'Tear in reality that allows instant transport and generates mana.',
    era: Era.Metropolis,
    baseCost: {
      [ResourceType.Stone]: 200,
      [ResourceType.Gems]: 80,
      [ResourceType.Mana]: 60,
    },
    costMultiplier: 1.15,
    maxLevel: 1,
    constructionTicks: 40,
    production: { [ResourceType.Mana]: 8 },
    techRequired: 'dimensional_rift',
  },
  [BuildingId.Oraculo]: {
    id: BuildingId.Oraculo,
    name: 'Oraculo',
    description: 'All-seeing oracle that reveals the map and boosts intelligence.',
    era: Era.Metropolis,
    baseCost: {
      [ResourceType.Stone]: 250,
      [ResourceType.Gems]: 60,
      [ResourceType.Mana]: 40,
    },
    costMultiplier: 1.15,
    maxLevel: 1,
    constructionTicks: 35,
    happinessBonus: 8,
    techRequired: 'divination',
  },
  [BuildingId.ForjaAncestral]: {
    id: BuildingId.ForjaAncestral,
    name: 'Forja Ancestral',
    description: 'Legendary forge that produces all resources at an extraordinary rate.',
    era: Era.Metropolis,
    baseCost: {
      [ResourceType.Iron]: 300,
      [ResourceType.Gems]: 100,
      [ResourceType.Mana]: 80,
      [ResourceType.Stone]: 200,
    },
    costMultiplier: 1.15,
    maxLevel: 1,
    constructionTicks: 50,
    production: {
      [ResourceType.Wood]: 10,
      [ResourceType.Food]: 10,
      [ResourceType.Stone]: 10,
      [ResourceType.Iron]: 10,
      [ResourceType.Gems]: 3,
      [ResourceType.Mana]: 3,
    },
    techRequired: 'ancestral_knowledge',
  },
};
