import { TechDefinition } from '../types/tech.js';
import { Era } from '../types/buildings.js';

export const TECH_DEFINITIONS: TechDefinition[] = [
  // ─── Era 1: Aldea (no prerequisites) ────────────────────
  {
    id: 'agriculture',
    name: 'Agricultura',
    description: 'Basic farming techniques that improve food production.',
    era: Era.Aldea,
    researchTicks: 10,
    cost: { gems: 2 },
    prerequisites: [],
    unlocks: ['granja_upgrade'],
  },
  {
    id: 'woodworking',
    name: 'Carpinteria',
    description: 'Advanced lumber processing methods.',
    era: Era.Aldea,
    researchTicks: 10,
    cost: { gems: 2 },
    prerequisites: [],
    unlocks: ['aserradero_upgrade'],
  },
  {
    id: 'mining_basics',
    name: 'Mineria Basica',
    description: 'Fundamental mining techniques for extracting stone and ore.',
    era: Era.Aldea,
    researchTicks: 12,
    cost: { gems: 3 },
    prerequisites: [],
    unlocks: ['mina_upgrade'],
  },
  {
    id: 'masonry',
    name: 'Albanaleria',
    description: 'Stone construction techniques enabling walls and towers.',
    era: Era.Aldea,
    researchTicks: 15,
    cost: { gems: 3 },
    prerequisites: ['mining_basics'],
    unlocks: ['torre'],
  },

  // ─── Era 2: Pueblo ──────────────────────────────────────
  {
    id: 'ironworking',
    name: 'Herreria',
    description: 'Smelting and forging iron into tools and weapons.',
    era: Era.Pueblo,
    researchTicks: 20,
    cost: { gems: 5 },
    prerequisites: ['mining_basics'],
    unlocks: ['herreria'],
  },
  {
    id: 'military_tactics',
    name: 'Tacticas Militares',
    description: 'Organized military formations and training disciplines.',
    era: Era.Pueblo,
    researchTicks: 20,
    cost: { gems: 5 },
    prerequisites: ['ironworking'],
    unlocks: ['cuartel', 'soldier', 'archer'],
  },
  {
    id: 'horseback_riding',
    name: 'Equitacion',
    description: 'Taming and riding horses for mounted combat.',
    era: Era.Pueblo,
    researchTicks: 25,
    cost: { gems: 6 },
    prerequisites: ['military_tactics'],
    unlocks: ['cavalry'],
  },
  {
    id: 'navigation',
    name: 'Navegacion',
    description: 'Seafaring techniques that open maritime trade routes.',
    era: Era.Pueblo,
    researchTicks: 22,
    cost: { gems: 5 },
    prerequisites: ['woodworking'],
    unlocks: ['puerto'],
  },
  {
    id: 'writing',
    name: 'Escritura',
    description: 'Written language that enables knowledge preservation.',
    era: Era.Pueblo,
    researchTicks: 18,
    cost: { gems: 4 },
    prerequisites: ['agriculture'],
    unlocks: ['biblioteca'],
  },
  {
    id: 'mysticism',
    name: 'Misticismo',
    description: 'Ancient rituals that channel supernatural energies.',
    era: Era.Pueblo,
    researchTicks: 25,
    cost: { gems: 6, mana: 3 },
    prerequisites: ['writing'],
    unlocks: ['templo', 'mana_production'],
  },
  {
    id: 'espionage',
    name: 'Espionaje',
    description: 'Covert intelligence gathering and sabotage techniques.',
    era: Era.Pueblo,
    researchTicks: 22,
    cost: { gems: 5 },
    prerequisites: ['military_tactics'],
    unlocks: ['spy'],
  },

  // ─── Era 3: Ciudad ──────────────────────────────────────
  {
    id: 'education',
    name: 'Educacion',
    description: 'Systematic education that accelerates all research.',
    era: Era.Ciudad,
    researchTicks: 30,
    cost: { gems: 10, mana: 5 },
    prerequisites: ['writing', 'mysticism'],
    unlocks: ['universidad'],
  },
  {
    id: 'fortification',
    name: 'Fortificacion',
    description: 'Advanced defensive engineering for impregnable walls.',
    era: Era.Ciudad,
    researchTicks: 30,
    cost: { gems: 10 },
    prerequisites: ['masonry', 'ironworking'],
    unlocks: ['fortaleza'],
  },
  {
    id: 'currency',
    name: 'Sistema Monetario',
    description: 'Standardized currency that enables complex financial instruments.',
    era: Era.Ciudad,
    researchTicks: 25,
    cost: { gems: 8 },
    prerequisites: ['navigation', 'writing'],
    unlocks: ['banco'],
  },
  {
    id: 'guilds',
    name: 'Gremios',
    description: 'Professional guilds that coordinate and optimize production.',
    era: Era.Ciudad,
    researchTicks: 28,
    cost: { gems: 8 },
    prerequisites: ['currency'],
    unlocks: ['gremio'],
  },
  {
    id: 'entertainment',
    name: 'Entretenimiento',
    description: 'Public entertainment that keeps citizens happy and productive.',
    era: Era.Ciudad,
    researchTicks: 20,
    cost: { gems: 6 },
    prerequisites: ['education'],
    unlocks: ['arena'],
  },
  {
    id: 'astronomy',
    name: 'Astronomia',
    description: 'Study of celestial bodies that reveals the secrets of mana.',
    era: Era.Ciudad,
    researchTicks: 35,
    cost: { gems: 12, mana: 8 },
    prerequisites: ['education', 'mysticism'],
    unlocks: ['observatorio'],
  },
  {
    id: 'siege_warfare',
    name: 'Guerra de Asedio',
    description: 'Techniques for constructing and deploying siege engines.',
    era: Era.Ciudad,
    researchTicks: 30,
    cost: { gems: 10 },
    prerequisites: ['fortification', 'horseback_riding'],
    unlocks: ['catapult'],
  },
  {
    id: 'arcane_arts',
    name: 'Artes Arcanas',
    description: 'Mastery of magical combat techniques.',
    era: Era.Ciudad,
    researchTicks: 35,
    cost: { gems: 10, mana: 12 },
    prerequisites: ['mysticism', 'military_tactics'],
    unlocks: ['mage'],
  },

  // ─── Era 4: Metropolis ──────────────────────────────────
  {
    id: 'architecture',
    name: 'Gran Arquitectura',
    description: 'Monumental architecture that enables world wonders.',
    era: Era.Metropolis,
    researchTicks: 50,
    cost: { gems: 25, mana: 15 },
    prerequisites: ['fortification', 'guilds'],
    unlocks: ['maravilla'],
  },
  {
    id: 'dimensional_rift',
    name: 'Fisura Dimensional',
    description: 'Tearing the fabric of reality to create portals between realms.',
    era: Era.Metropolis,
    researchTicks: 60,
    cost: { gems: 30, mana: 30 },
    prerequisites: ['astronomy', 'arcane_arts'],
    unlocks: ['portal'],
  },
  {
    id: 'divination',
    name: 'Adivinacion',
    description: 'The power to see across time and space.',
    era: Era.Metropolis,
    researchTicks: 45,
    cost: { gems: 20, mana: 20 },
    prerequisites: ['astronomy', 'espionage'],
    unlocks: ['oraculo'],
  },
  {
    id: 'ancestral_knowledge',
    name: 'Conocimiento Ancestral',
    description: 'Unlocking the ancient secrets of a lost civilization.',
    era: Era.Metropolis,
    researchTicks: 55,
    cost: { gems: 30, mana: 25 },
    prerequisites: ['dimensional_rift', 'architecture'],
    unlocks: ['forja_ancestral'],
  },
];
