import { UnitType, UnitDefinition } from '../types/units.js';
import { Era } from '../types/buildings.js';
import { ResourceType } from '../types/resources.js';

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  [UnitType.Soldier]: {
    type: UnitType.Soldier,
    name: 'Soldado',
    attack: 30,
    defense: 25,
    health: 100,
    speed: 2,
    foodPerTick: 1,
    trainingCost: { [ResourceType.Food]: 20, [ResourceType.Iron]: 10 },
    trainingTicks: 3,
    era: Era.Aldea,
    strongAgainst: UnitType.Archer,
    weakAgainst: UnitType.Cavalry,
  },
  [UnitType.Archer]: {
    type: UnitType.Archer,
    name: 'Arquero',
    attack: 35,
    defense: 15,
    health: 70,
    speed: 2,
    foodPerTick: 1,
    trainingCost: { [ResourceType.Food]: 15, [ResourceType.Wood]: 20 },
    trainingTicks: 3,
    era: Era.Aldea,
    strongAgainst: UnitType.Cavalry,
    weakAgainst: UnitType.Soldier,
  },
  [UnitType.Cavalry]: {
    type: UnitType.Cavalry,
    name: 'Caballeria',
    attack: 40,
    defense: 20,
    health: 90,
    speed: 4,
    foodPerTick: 2,
    trainingCost: { [ResourceType.Food]: 30, [ResourceType.Wood]: 10, [ResourceType.Iron]: 15 },
    trainingTicks: 5,
    era: Era.Pueblo,
    strongAgainst: UnitType.Soldier,
    weakAgainst: UnitType.Archer,
  },
  [UnitType.Lancer]: {
    type: UnitType.Lancer,
    name: 'Lancero',
    attack: 25,
    defense: 35,
    health: 110,
    speed: 2,
    foodPerTick: 1,
    trainingCost: { [ResourceType.Food]: 20, [ResourceType.Iron]: 20 },
    trainingTicks: 4,
    era: Era.Pueblo,
    strongAgainst: UnitType.Cavalry,
    weakAgainst: UnitType.Catapult,
  },
  [UnitType.Catapult]: {
    type: UnitType.Catapult,
    name: 'Catapulta',
    attack: 55,
    defense: 5,
    health: 60,
    speed: 1,
    foodPerTick: 2,
    trainingCost: { [ResourceType.Wood]: 50, [ResourceType.Iron]: 30, [ResourceType.Stone]: 20 },
    trainingTicks: 8,
    era: Era.Ciudad,
    strongAgainst: UnitType.Lancer,
    weakAgainst: UnitType.Cavalry,
  },
  [UnitType.Spy]: {
    type: UnitType.Spy,
    name: 'Espia',
    attack: 15,
    defense: 10,
    health: 50,
    speed: 5,
    foodPerTick: 1,
    trainingCost: { [ResourceType.Food]: 15, [ResourceType.Gems]: 5 },
    trainingTicks: 6,
    era: Era.Pueblo,
  },
  [UnitType.Mage]: {
    type: UnitType.Mage,
    name: 'Mago',
    attack: 60,
    defense: 10,
    health: 60,
    speed: 2,
    foodPerTick: 2,
    trainingCost: { [ResourceType.Food]: 25, [ResourceType.Gems]: 10, [ResourceType.Mana]: 15 },
    trainingTicks: 10,
    era: Era.Ciudad,
    strongAgainst: UnitType.Soldier,
    weakAgainst: UnitType.Archer,
  },
};
